name: concurrency
run-name: concurrency 1 (${{ inputs.environment }})
on:
 workflow_dispatch:
   inputs:
     environment:
       description: "Environment"
       type: environment
       required: false
concurrency:
  group: ${{ github.event.inputs.environment }}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: self-hosted
    steps:
      - run: sleep 30
  
       
